-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,IFNULL(FREEZER_YN, 'N') AS FREEZER_YN FROM FOOD_WAREHOUSE WHERE ADDRESS LIKE'경기도%' ORDER BY WAREHOUSE_ID;

-- ORACLE에서는 NVL, MYSQL에서는 IFNULL
-- SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,NVL(FREEZER_YN, 'N') AS FREEZER_YN FROM FOOD_WAREHOUSE WHERE ADDRESS LIKE'경기도%' ORDER BY WAREHOUSE_ID;